name: CI

on: [push]

jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - uses: icrawl/action-tsc@v1

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: Run eslint
      run: |
        npx eslint --ext .js,.ts .

  tests:
    needs: ['type_check', 'lint']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: Run tests
      run: |
        npm run build --if-present
        npm test
      env:
        CI: 'true'
